-- MySQL Script generated by MySQL Workbench
-- Sun Dec  1 22:40:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lhd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lhd` ;

-- -----------------------------------------------------
-- Schema lhd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lhd` DEFAULT CHARACTER SET utf8 ;
USE `lhd` ;

-- -----------------------------------------------------
-- Table `lhd`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`users` ;

CREATE TABLE IF NOT EXISTS `lhd`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `idRole` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`role` ;

CREATE TABLE IF NOT EXISTS `lhd`.`role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`),
  CONSTRAINT `user_role`
    FOREIGN KEY (`idRole`)
    REFERENCES `lhd`.`users` (`idUsers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`teams` ;

CREATE TABLE IF NOT EXISTS `lhd`.`teams` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `userCreatedBy` INT NOT NULL,
  `idTeamType` INT NOT NULL,
  `idCategory` INT NOT NULL,
  `nameTeam` VARCHAR(45) NOT NULL,
  `timeCreatedBy` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `score` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idTeam`),
  INDEX `team_user_idx` (`userCreatedBy` ASC) ,
  CONSTRAINT `team_user`
    FOREIGN KEY (`userCreatedBy`)
    REFERENCES `lhd`.`users` (`idUsers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`categories` ;

CREATE TABLE IF NOT EXISTS `lhd`.`categories` (
  `idCategory` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`),
  CONSTRAINT `categories_team`
    FOREIGN KEY (`idCategory`)
    REFERENCES `lhd`.`teams` (`idTeam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`hackers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`hackers` ;

CREATE TABLE IF NOT EXISTS `lhd`.`hackers` (
  `idHacker` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(8) NOT NULL,
  `birthDate` DATE NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registered` TINYINT NOT NULL,
  `checkin` TINYINT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHacker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`team_hackers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`team_hackers` ;

CREATE TABLE IF NOT EXISTS `lhd`.`team_hackers` (
  `idTeamHacker` INT NOT NULL AUTO_INCREMENT,
  `idTeam` INT NOT NULL,
  `idHacker` INT NOT NULL,
  PRIMARY KEY (`idTeamHacker`),
  INDEX `team_hacker_idx` (`idHacker` ASC) ,
  INDEX `team_team_idx` (`idTeam` ASC) ,
  CONSTRAINT `team_hacker`
    FOREIGN KEY (`idHacker`)
    REFERENCES `lhd`.`hackers` (`idHacker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `team_team`
    FOREIGN KEY (`idTeam`)
    REFERENCES `lhd`.`teams` (`idTeam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`judgesCategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`judgesCategories` ;

CREATE TABLE IF NOT EXISTS `lhd`.`judgesCategories` (
  `idJudgesCategories` INT NOT NULL AUTO_INCREMENT,
  `idJudge` INT NULL,
  `idCategory` INT NULL,
  PRIMARY KEY (`idJudgesCategories`),
  INDEX `judge_user_idx` (`idJudge` ASC) ,
  INDEX `judge_category_idx` (`idCategory` ASC) ,
  CONSTRAINT `judge_user`
    FOREIGN KEY (`idJudge`)
    REFERENCES `lhd`.`users` (`idUsers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `judge_category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `lhd`.`categories` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lhd`.`team_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lhd`.`team_type` ;

CREATE TABLE IF NOT EXISTS `lhd`.`team_type` (
  `idTeamType` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeamType`),
  CONSTRAINT `type`
    FOREIGN KEY (`idTeamType`)
    REFERENCES `lhd`.`teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
